<?php
declare(strict_types=1);

/**
 * Reference catalog used only to seed program-code lookup data. Runtime import
 * matching reads the database table created by the corresponding migration.
 */
return [
    // Computing, IT, and digital arts
    ['Bachelor of Science in Computer Science', 'BSCS'],
    ['Bachelor of Science in Information Technology', 'BSIT'],
    ['Bachelor of Science in Information Systems', 'BSIS'],
    ['Bachelor of Science in Cybersecurity', 'BSCyS'],
    ['Bachelor of Science in Data Science', 'BSDS'],
    ['Bachelor of Science in Software Engineering', 'BSSE'],
    ['Bachelor of Science in Entertainment and Multimedia Computing', 'BSEMC'],
    ['Bachelor of Science in Game Development', 'BSGD'],
    ['Bachelor of Science in Animation', 'BSAnim'],
    ['Associate in Computer Technology', 'ACT'],

    // Engineering disciplines
    ['Bachelor of Science in Civil Engineering', 'BSCE'],
    ['Bachelor of Science in Mechanical Engineering', 'BSME'],
    ['Bachelor of Science in Electrical Engineering', 'BSEE'],
    ['Bachelor of Science in Electronics Engineering', 'BSECE'],
    ['Bachelor of Science in Computer Engineering', 'BSCpE'],
    ['Bachelor of Science in Chemical Engineering', 'BSChE'],
    ['Bachelor of Science in Industrial Engineering', 'BSIE'],
    ['Bachelor of Science in Aerospace Engineering', 'BSAE'],
    ['Bachelor of Science in Marine Engineering', 'BSMarE'],
    ['Bachelor of Science in Mining Engineering', 'BSEM'],
    ['Bachelor of Science in Geodetic Engineering', 'BSGE'],
    ['Bachelor of Science in Environmental and Sanitary Engineering', 'BSESE'],
    ['Bachelor of Science in Agricultural and Biosystems Engineering', 'BSABE'],
    ['Bachelor of Science in Materials Engineering', 'BSMatE'],
    ['Bachelor of Science in Petroleum Engineering', 'BSPetE'],

    // Medical, allied health, and rehabilitation sciences
    ['Bachelor of Science in Nursing', 'BSN'],
    ['Bachelor of Science in Medical Technology', 'BSMT', ['BSMLS']],
    ['Bachelor of Science in Medical Laboratory Science', 'BSMLS', ['BSMT']],
    ['Bachelor of Science in Medical Technology / Medical Laboratory Science', 'BSMLS', ['BSMT']],
    ['Bachelor of Science in Pharmacy', 'BSPharm'],
    ['Bachelor of Science in Physical Therapy', 'BSPT'],
    ['Bachelor of Science in Occupational Therapy', 'BSOT'],
    ['Bachelor of Science in Radiologic Technology', 'BSRT'],
    ['Bachelor of Science in Respiratory Therapy', 'BSReT'],
    ['Bachelor of Science in Nutrition and Dietetics', 'BSND'],
    ['Bachelor of Science in Midwifery', 'BSMid'],
    ['Bachelor of Science in Speech-Language Pathology', 'BSSLP'],
    ['Bachelor of Science in Sports Science', 'BSSS'],
    ['Bachelor of Science in Public Health', 'BSPH'],
    ['Bachelor of Science in Human Biology', 'BSHumanBio'],

    // Business, management, and finance
    ['Bachelor of Science in Accountancy', 'BSA'],
    ['Bachelor of Science in Management Accounting', 'BSMA'],
    ['Bachelor of Science in Internal Auditing', 'BSIA'],
    ['Bachelor of Science in Business Administration Major in Marketing Management', 'BSBA-MM'],
    ['Bachelor of Science in Business Administration Major in Financial Management', 'BSBA-FM'],
    ['Bachelor of Science in Business Administration Major in Human Resource Management', 'BSBA-HRM'],
    ['Bachelor of Science in Business Administration Major in Operations Management', 'BSBA-OM'],
    ['Bachelor of Science in Entrepreneurship', 'BSEntrep'],
    ['Bachelor of Science in Real Estate Management', 'BSREM'],
    ['Bachelor of Science in Customs Administration', 'BSCA'],
    ['Bachelor of Science in Office Administration', 'BSOA'],
    ['Bachelor of Science in Economics', 'BSEcon'],

    // Hospitality, tourism, and culinary
    ['Bachelor of Science in Hospitality Management', 'BSHM'],
    ['Bachelor of Science in Tourism Management', 'BSTM'],
    ['Bachelor of Science in Culinary Management', 'BSCM'],
    ['Bachelor of Science in Cruise Line Operations', 'BSCLO'],

    // Design, architecture, and fine arts
    ['Bachelor of Science in Architecture', 'BSArch'],
    ['Bachelor of Science in Interior Design', 'BSID'],
    ['Bachelor of Science in Landscape Architecture', 'BSLA'],
    ['Bachelor of Fine Arts Major in Visual Communication', 'BFA-VC'],
    ['Bachelor of Fine Arts Major in Industrial Design', 'BFA-ID'],
    ['Bachelor of Fine Arts Major in Painting', 'BFA-P'],
    ['Bachelor of Arts in Multimedia Arts', 'BAMMA'],
    ['Bachelor of Science in Fashion Design and Technology', 'BSFDT'],

    // Teacher education and specializations
    ['Bachelor of Elementary Education', 'BEEd'],
    ['Bachelor of Early Childhood Education', 'BECEd'],
    ['Bachelor of Special Needs Education', 'BSNEd'],
    ['Bachelor of Secondary Education Major in English', 'BSEd-ENG'],
    ['Bachelor of Secondary Education Major in Mathematics', 'BSEd-MATH'],
    ['Bachelor of Secondary Education Major in Science', 'BSEd-SCI'],
    ['Bachelor of Secondary Education Major in Social Studies', 'BSEd-SS'],
    ['Bachelor of Secondary Education Major in Filipino', 'BSEd-FIL'],
    ['Bachelor of Culture and Arts Education', 'BCAEd'],
    ['Bachelor of Physical Education', 'BPEd'],
    ['Bachelor of Technical-Vocational Teacher Education', 'BTVTEd'],
    ['Bachelor of Special Needs Education - Generalist', 'BSNEd-Gen'],
    ['Bachelor of Special Needs Education major in Teaching Learners with Visual Impairments', 'BSNEd-VI'],
    ['Bachelor of Special Needs Education major in Teaching Learners with Hearing Impairments', 'BSNEd-HI'],
    ['Bachelor of Special Needs Education major in Teaching Learners with Intellectual Disabilities', 'BSNEd-ID'],
    ['Bachelor of Special Needs Education major in Early Childhood Special Needs Education', 'BSNEd-ECSNEd'],
    ['Bachelor of Secondary Education major in General Science', 'BSEd-Sci'],
    ['Bachelor of Secondary Education major in Biology', 'BSEd-Bio'],
    ['Bachelor of Secondary Education major in Chemistry', 'BSEd-Chem'],
    ['Bachelor of Secondary Education major in Physics', 'BSEd-Phys'],
    ['Bachelor of Secondary Education major in Values Education', 'BSEd-VE'],
    ['Bachelor of Technical-Vocational Teacher Education major in Automotive Technology', 'BTVTEd-Auto'],
    ['Bachelor of Technical-Vocational Teacher Education major in Electrical Technology', 'BTVTEd-Elex'],
    ['Bachelor of Technical-Vocational Teacher Education major in Electronics Technology', 'BTVTEd-Elxn'],
    ['Bachelor of Technical-Vocational Teacher Education major in HVAC Technology', 'BTVTEd-HVAC'],
    ['Bachelor of Technical-Vocational Teacher Education major in Mechanical Technology', 'BTVTEd-Mech'],
    ['Bachelor of Technical-Vocational Teacher Education major in Welding and Fabrication Technology', 'BTVTEd-WFT'],
    ['Bachelor of Technical-Vocational Teacher Education major in Civil and Trade Technology', 'BTVTEd-CTT'],
    ['Bachelor of Technical-Vocational Teacher Education major in Garments, Fashion and Design', 'BTVTEd-GFD'],
    ['Bachelor of Technical-Vocational Teacher Education major in Food and Service Management', 'BTVTEd-FSM'],
    ['Bachelor of Technical-Vocational Teacher Education major in Beauty Care and Wellness', 'BTVTEd-BCW'],
    ['Bachelor of Technology and Livelihood Education major in Home Economics', 'BTLEd-HE'],
    ['Bachelor of Technology and Livelihood Education major in Industrial Arts', 'BTLEd-IA'],
    ['Bachelor of Technology and Livelihood Education major in Information and Communications Technology', 'BTLEd-ICT'],
    ['Bachelor of Technology and Livelihood Education major in Agri-Fishery Arts', 'BTLEd-AFA'],
    ['Bachelor of Science in Exercise and Sports Sciences major in Fitness and Sports Coaching', 'BSESS-FSC'],
    ['Bachelor of Science in Exercise and Sports Sciences major in Fitness and Sports Management', 'BSESS-FSM'],
    ['Bachelor of Library and Information Science', 'BLIS'],

    // Social sciences, law, and public safety
    ['Bachelor of Science in Criminology', 'BSCrim'],
    ['Bachelor of Science in Psychology', 'BSPsych'],
    ['Bachelor of Arts in Psychology', 'BAPsych'],
    ['Bachelor of Science in Social Work', 'BSSW'],
    ['Bachelor of Arts in Political Science', 'BAPS'],
    ['Bachelor of Arts in International Studies', 'BAIS'],
    ['Bachelor of Arts in Sociology', 'BASocio'],
    ['Bachelor of Arts in History', 'BAHist'],
    ['Bachelor of Arts in Anthropology', 'BAAnthro'],
    ['Bachelor of Science in Public Administration', 'BSPA'],
    ['Bachelor of Science in Forensic Science', 'BSFS'],

    // Humanities, media, and communications
    ['Bachelor of Arts in Communication', 'BAComm'],
    ['Bachelor of Arts in Journalism', 'BAJourn'],
    ['Bachelor of Arts in Broadcasting', 'BABroad'],
    ['Bachelor of Arts in English Language Studies', 'BAELS'],
    ['Bachelor of Arts in Literature', 'BALit'],
    ['Bachelor of Arts in Philosophy', 'BAPhil'],
    ['Bachelor of Arts in Theater Arts', 'BATA'],
    ['Bachelor of Arts in Creative Writing', 'BACW'],
    ['Bachelor of Music', 'BMus'],

    // Pure and applied sciences
    ['Bachelor of Science in Biology', 'BSBio'],
    ['Bachelor of Science in Chemistry', 'BSChem'],
    ['Bachelor of Science in Physics', 'BSPhys'],
    ['Bachelor of Science in Mathematics', 'BSMath'],
    ['Bachelor of Science in Statistics', 'BSStat'],
    ['Bachelor of Science in Environmental Science', 'BSES'],
    ['Bachelor of Science in Food Technology', 'BSFT'],
    ['Bachelor of Science in Biochemistry', 'BSBCh'],
    ['Bachelor of Science in Applied Physics', 'BSAP'],
    ['Bachelor of Science in Geology', 'BSGeo'],
    ['Bachelor of Science in Marine Biology', 'BSMB'],

    // Agriculture, forestry, and aviation
    ['Bachelor of Science in Agriculture', 'BSAgr'],
    ['Bachelor of Science in Forestry', 'BSF'],
    ['Bachelor of Science in Fisheries', 'BSFi'],
    ['Bachelor of Science in Agroforestry', 'BSAF'],
    ['Bachelor of Science in Marine Transportation', 'BSMT'],
    ['Bachelor of Science in Aeronautical Engineering', 'BSAeroE'],
    ['Bachelor of Science in Aviation Electronics Technology', 'BSAET'],
    ['Bachelor of Science in Air Transportation', 'BSAT'],
];
